<?php
$parameters = array(
    'db_driver' => 'pdo_mysql',
    'db_table_prefix' => null,
    'db_host' => getenv('DB_HOST') ?: '127.0.0.1',
    'db_port' => getenv('DB_PORT') ?: '3306',
    'db_name' => getenv('DB_NAME') ?: 'mautic',
    'db_user' => getenv('DB_USER') ?: 'root',
    'db_password' => getenv('DB_PASSWD') ?: 'root',
    'db_backup_tables' => 0,
    'db_backup_prefix' => 'bak_',
    'db_server_version' => '5.6.33',
    'mailer_from_name' => getenv('MAILER_FROM_NAME') ?: 'Web Developer',
    'mailer_from_email' => getenv('MAILER_FROM_EMAIL') ?: 'web@developer.com',
    'mailer_transport' => 'mail',
    'mailer_host' => null,
    'mailer_port' => null,
    'mailer_user' => 'root',
    'mailer_password' => 'root',
    'mailer_encryption' => null,
    'mailer_auth_mode' => null,
    'mailer_spool_type' => 'file',
    'mailer_spool_path' => '%kernel.root_dir%/spool',
    'secret_key' => getenv('SECRET_KEY') ?: '3e29c87bddfbfc8e59d004581da4fa9f5c9fe0a9f1f90a244a38e2e5600c2800',
    'site_url' => getenv('APP_URL') ?: 'http://mautic.vm',
);
